.\SongInserter.exe .\DemoSongs\asterix_challenge_level.gb .\DemoSongs\asterix_challenge_level.gbs 
.\SongInserter.exe .\DemoSongs\asterix_stage.gb .\DemoSongs\asterix_stage.gbs 
.\SongInserter.exe .\DemoSongs\asterix_stage1.gb .\DemoSongs\asterix_stage1.gbs 
.\SongInserter.exe .\DemoSongs\asterix_stage2.gb .\DemoSongs\asterix_stage2.gbs 
.\SongInserter.exe .\DemoSongs\bergentruckung.gb .\DemoSongs\bergentruckung.gbs 
.\SongInserter.exe .\DemoSongs\crystal_caverns.gb .\DemoSongs\crystal_caverns.gbs 
.\SongInserter.exe .\DemoSongs\darkman.gb .\DemoSongs\darkman.gbs 
.\SongInserter.exe .\DemoSongs\die_maus.gb .\DemoSongs\die_maus.gbs 
.\SongInserter.exe .\DemoSongs\dr_wright.gb .\DemoSongs\dr_wright.gbs 
.\SongInserter.exe .\DemoSongs\jingle_bells.gb .\DemoSongs\jingle_bells.gbs 
.\SongInserter.exe .\DemoSongs\jurassic_park_bonus.gb .\DemoSongs\jurassic_park_bonus.gbs 
.\SongInserter.exe .\DemoSongs\jurassic_park_lvl2.gb .\DemoSongs\jurassic_park_lvl2.gbs 
.\SongInserter.exe .\DemoSongs\kraken_of_the_sea.gb .\DemoSongs\kraken_of_the_sea.gbs 
.\SongInserter.exe .\DemoSongs\ltcc_zoo.gb .\DemoSongs\ltcc_zoo.gbs 
.\SongInserter.exe .\DemoSongs\megaman_v_stageselect.gb .\DemoSongs\megaman_v_stageselect.gbs 
.\SongInserter.exe .\DemoSongs\mohenjodaro_usas.gb .\DemoSongs\mohenjodaro_usas.gbs 
.\SongInserter.exe .\DemoSongs\monster_max.gb .\DemoSongs\monster_max.gbs 
.\SongInserter.exe .\DemoSongs\ottifanten_woods.gb .\DemoSongs\ottifanten_woods.gbs 
.\SongInserter.exe .\DemoSongs\pokemon_route_01.gb .\DemoSongs\pokemon_route_01.gbs 
.\SongInserter.exe .\DemoSongs\shop_theme.gb .\DemoSongs\shop_theme.gbs 
.\SongInserter.exe .\DemoSongs\smurf_nightmare_well.gb .\DemoSongs\smurf_nightmare_well.gbs 
.\SongInserter.exe .\DemoSongs\soldier_blade_op1.gb .\DemoSongs\soldier_blade_op1.gbs 
.\SongInserter.exe .\DemoSongs\super_star_soldier_area1.gb .\DemoSongs\super_star_soldier_area1.gbs 
.\SongInserter.exe .\DemoSongs\super_star_soldier_area2.gb .\DemoSongs\super_star_soldier_area2.gbs 
.\SongInserter.exe .\DemoSongs\tomjerry_level3.gb .\DemoSongs\tomjerry_level3.gbs 
.\SongInserter.exe .\DemoSongs\towntheme.gb .\DemoSongs\towntheme.gbs 
.\SongInserter.exe .\DemoSongs\trouballs_title.gb .\DemoSongs\trouballs_title.gbs 
.\SongInserter.exe .\DemoSongs\undertale_death.gb .\DemoSongs\undertale_death.gbs 
.\SongInserter.exe .\DemoSongs\usas_jubaruins.gb .\DemoSongs\usas_jubaruins.gbs 
.\SongInserter.exe .\DemoSongs\v_rally_carselect.gb .\DemoSongs\v_rally_carselect.gbs 
